### ISSUE TITLE
Selection Not Working With Meshes on OSX

### ISSUE THREAD

**Issue by weshoke** [nmwsharp/polyscope-py#3]
After pip-installing the latest and running this code, the selection UI doesn't show up when clicking on the mesh.  Everything works fine with the C++ library when I build that from source.

```
import polyscope as pscope

pscope.set_program_name("Demo")
pscope.init()

# create mesh

ps_mesh = pscope.register_surface_mesh("ps-mesh", mesh.vertices, mesh.faces)
if mesh.normals is not None:
    ps_mesh.add_vector_quantity("normals", mesh.normals, enabled=False)

if mesh.uvs is not None:
    ps_mesh.add_parameterization_quantity("uv", mesh.uvs, checker_size=3e-4, viz_style="checker", enabled=True)

if mesh.face_ids is not None:
    ps_mesh.add_scalar_quantity("face_ids", mesh.face_ids, defined_on="faces", enabled=True)

pscope.show()
```

**Comment by weshoke** [comment]
I can confirm that building the python bindings from source and running the demo exhibits the same behavior

**Comment by weshoke** [comment]
I tried looking into this, but couldn't figure it out.  Clearing the renderbuffer attached to COLOR_ATTACHMENT0 of the framebuffer works and when a readpixel happens, that color is returned.  However, the drawing of the geometry with the pick shader has no effect.  The transforms supplied to the shader all look good.  I'm really not sure what the difference is.

**Comment by weshoke** [comment]
Thanks for checking it out.  This has to be something super obscure.  I really couldn't make heads or tails of where the issue is.

**Comment by nmwsharp** [comment]
Ah, I dug in more, I think I have it figured out.

Updating to the latest version of the upstream C++ repo and rebuilding the bindings seems to fix the issue. I thing this is probably the commit that was needed, though I didn't bisect to be sure. https://github.com/nmwsharp/polyscope/commit/b1b0fe4f1649000b93f0dcfebb70d53b45544be3

I'm generating a new version of the bindings on CI now; should be available on pip/conda before too long.

**Comment by weshoke** [comment]
I can confirm that picking works now.  Thank you!

**Comment by nmwsharp** [comment]
No problem, thank you for reporting!
