### ISSUE TITLE
use add_color_quantity to texture on uv not working

### ISSUE THREAD

**Issue by stallboy** [nmwsharp/polyscope-py#38]
Hi @nmwsharp !

Thanks for this amazing package! 

```python

    ps.init()
    fn = 'data/our_faces/face_lod0_with_uv.obj'

    mesh : Trimesh = trimesh.load(fn, process=False)
    verts = mesh.vertices
    faces = mesh.faces
    uv = mesh.visual.uv
    print("verts shape:", verts.shape, ',uv shape:', uv.shape)
    ps_mesh = ps.register_surface_mesh("my_mesh", verts, faces, color=(0.8, 0.8, 0.8), edge_width=0.8)

    ps_mesh.add_parameterization_quantity("my_uv", uv, defined_on='vertices', enabled=True)

    dims = (200, 200, 3)
    color_vals = np.random.randint(0, 255, size=dims)  # dummy placeholder image data
    color_vals = color_vals / 255.
    ps_mesh.add_color_quantity("my_img", color_vals,
                                defined_on='texture', param_name="my_uv",
                                enabled=True)

    ps.add_color_image_quantity("color_img", color_vals, enabled=True,
                                show_fullscreen=False, show_in_camera_billboard=False, transparency=0.5)

    ps.show()

```

the texture not working, the noise texture is expected on the surface of mesh, but it does NOT.
![image](https://github.com/nmwsharp/polyscope-py/assets/559049/11d533b1-8a17-46e8-bd3d-3b7037efa259)

then I checked the uv by enable the my_uv(vertex parameterization), it looks ok. so the problem is not on UV. 
![image](https://github.com/nmwsharp/polyscope-py/assets/559049/4859a614-f79d-42c4-8e46-218907f14125)

Thanks.

**Comment by nmwsharp** [comment]
Can you try updating to the latest version (2.2.1) and testing again? I believe this may have just been fixed.

**Comment by stallboy** [comment]
![image](https://github.com/nmwsharp/polyscope-py/assets/559049/04cbd51b-2481-46cc-b6ea-25fa86a0082c)
fixed!, thanks @nmwsharp
