### ISSUE TITLE
Adding ImGui For Custom Bindings

### ISSUE THREAD

**Issue by weshoke** [nmwsharp/polyscope-py#8]
Here's my WIP on adding ImGui https://github.com/subscale/polyscope-py/blob/add-gui-features/src/cpp/imgui.cpp

I took the following approach:
* use lower case snake_case for Python method names, so `ImGui::TreeNodeEx` becomes `tree_node_ex`
* No "Python" wrapper for the PyBind11 bindings.  Just use the PyBind11 bindings directly.  In general, I wonder if the "pass thru" python functions shouldn't just be accessed directly
* ImGui API argument types are mapped to Python types via PyBind11 such that native Python types can be used like arrays and tuples.  I took this approach to avoid having to wrap things in Python so that native Python types would work.

`float v[2]` -> `std::array<float, 2>` 

```
 m.def(
        "drag_float2",
        [](const char* label,
           const std::array<float, 2>& v,
           float v_speed,
           float v_min,
           float v_max,
           const char* format,
           float power) {
            auto v_ = v;
            auto clicked =
                ImGui::DragFloat2(label, v_.data(), v_speed, v_min, v_max, format, power);
            return std::make_tuple(clicked, v_);
        },
        py::arg("label"),
        py::arg("v"),
        py::arg("v_speed") = 1.0f,
        py::arg("v_min") = 0.0f,
        py::arg("v_max") = 0.0f,
        py::arg("format") = "%.3f",
        py::arg("power") = 1.0f);
```

`ImVecN` types are translated into `std::tuple`

```
Vec2T from_vec2(const ImVec2& v) { return std::make_tuple(v.x, v.y); }
Vec4T from_vec4(const ImVec4& v) { return std::make_tuple(v.x, v.y, v.z, v.w); }
```

```
m.def(
        "progress_bar",
        [](float fraction, const Vec2T& size_arg) {
            ImGui::ProgressBar(fraction, to_vec2(size_arg));
        },
        py::arg("fraction"),
        py::arg("size_arg") = std::make_tuple(-1.f, 0.f));

m.def("get_cursor_pos", []() { return from_vec2(ImGui::GetCursorPos()); });
```

* Enums are modeled in an odd way, I need to fix it to use `py::enum_`

**Comment by weshoke** [comment]
@nmwsharp TL;DR if you're open to it, the major points to discuss IMHO would be about 
* enabling native Python types from the C++ side instead of using `glm` and the `imgui.py` wrapper
* Whether naming should be like the ImGui C++ names or converted to the typical python snake_case convetion

**Comment by nmwsharp** [comment]
Thanks for sharing! 

That's a ton of bindings, wow! Did you write those manually or use some tool to generate them?

I mostly think your strategies sound like good ones. A few comments below.

> snake case

This one I actually do disagree with a bit. I think we should keep the ImGui naming conventions exactly, even though that conflicts with the conventions used elsewhere polyscope-py. The reason why is that I don't want to have to write/maintain docs for each of the functions in these bindings :) If we keep the function names exactly, then I think it's fine to just refer people to `imgui.h` for documentation, whereas if we are renaming the functions then it is a bit more necessary to document them.

> no Python passthrough layer

This is reasonable. It cuts down on the work, and we _should_ be fine just binding the functions directly. And we can always add the passthrough layer later if it becomes necessary. 

It might be nice to set these up as an `imgui` submodule within the pybind11 bindings, so we invoke them like `import polyscope.imgui` etc. 

> mapping to ImGui types

Sounds reasonable. This is simpler, and I can't realllly think of any benefit to mapping into/out of the glm types.

**Comment by nmwsharp** [comment]
Those bindings from your branch are much more complete than what I had started, I'd be very happy to merge them in (possibly after some of the changes above), if that is something you're interested in.

**Comment by weshoke** [comment]
I did do these by hand.  It's not as much work as it seems.  For larger C libraries whose interface can update a couple of times a year, I'll generate the bindings with a script.  It didn't seem worth the effort when these can be done by hand in a couple of hours.

One question.  How should:

```
enum ImGuiCond_
{
    ImGuiCond_Always        = 1 << 0,   // Set the variable
    ImGuiCond_Once          = 1 << 1,   // Set the variable once per runtime session (only the first call with succeed)
    ImGuiCond_FirstUseEver  = 1 << 2,   // Set the variable if the object/window has no persistently saved data (no entry in .ini file)
    ImGuiCond_Appearing     = 1 << 3    // Set the variable if the object/window is appearing after being hidden/inactive (or the first time)
};
```

be translated?  What should the python code look like?


A few options for how the Python code could look.  What would be the most consistent with the idea of "not changing ImGui interface so that the ImGui docs are relevant?  Or does having something a bit more "Pythonic" get a little more weight in this case?


```
import polyscope_bindings.imgui as imgui
print(imgui.ImGuiCond.Appearing)
```

```
import polyscope_bindings.imgui as imgui
print(imgui.ImGuiCond_Appearing)
```

```
import polyscope_bindings.imgui as imgui
print(imgui.ImGuiCond_.Appearing)
```

**Comment by weshoke** [comment]
Here's a first take at the function bindings.  I'll wait to do the enums until I hear from you on the above.
https://github.com/subscale/polyscope-py/blob/callback-imgui/src/cpp/imgui.cpp

**Comment by nmwsharp** [comment]
Awesome!

> Translating enums

Good question. I think we _could_ emulate the C behavior and make them flags which respect `|`. It looks like that is what pyimgui does: https://pyimgui.readthedocs.io/en/latest/guide/window-flags.html. I'm not sure if it's possible to emit such bindings from pybind11.... I'd be okay with other solutions that are easier, for instance passing an iterable of enums which we then iterate through and union on the C++ side.

> Code style

My personal preference is `print(imgui.ImGuiCond_Appearing)`, again for the reason of just always matching C ImGui as closely as possible. But I'm open to other opinions there :)

**Comment by nmwsharp** [comment]
Additionally, I'd say it's very important that we not expose the `polyscope_bindings` package directly to the user; it should stay an internal detail so that we can change it transparently in the future if need be.

We can probably just forward all of the functions to the `polyscope` package namespace via something like `from polyscope_bindings  import *`, right? I'm always terrible at Python package structure and `__init__.py` rules.

**Comment by weshoke** [comment]
Yes, `polyscope_bindings import *` is totally viable.  I do that in other Python modules I've made with hybrid C++/Python bindings.  It works perfectly well.

For `print(imgui.ImGuiCond_Appearing)`, sounds good.  It's the most consistent with the function bindings style.  It would mean not making them Python enums though since Python enums are scoped to a class.  They'd instead be integer globals to the `polyscope_bindings.imgui` scope.

**Comment by weshoke** [comment]
https://github.com/nmwsharp/polyscope-py/pull/9
